// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jolerxrpmyhrrbplhegd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbGVyeHJwbXlocnJicGxoZWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTcwMTksImV4cCI6MjA2MDgzMzAxOX0.ZDubveV5tz-BC3qNAKYgkoYkiOfnDgmYd35NhjfG12I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);